name: Dependency Review

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    uses: eclipse-fennec/.github/.github/workflows/reusable-dependency-review.yml@4c8b1daf597d0ae439253b59c42d7e52049d5137 # v1.1.2
