name: Dependency Review

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    uses: eclipse-fennec/.github/.github/workflows/reusable-dependency-review.yml@2a98ad6e2459556b858e1273bff2f8d87fc11a06 # v1.3.0
