name: Documentation

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    uses: eclipse-fennec/.github/.github/workflows/reusable-docs.yml@4c8b1daf597d0ae439253b59c42d7e52049d5137 # v1.1.2
